version: 2.1

jobs:
  train-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Load .env
          command: |
            echo "MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI" > .env
            echo "EXPERIMENT_NAME=$EXPERIMENT_NAME" >> .env

      - run:
          name: Run Pytest
          command: |
            pytest tests/

      - run:
          name: Train Model
          command: |
            python train.py

workflows:
  version: 2
  train-workflow:
    jobs:
      - train-and-test
